name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run isort
        run: |
          isort --check src
      - name: Run black
        run: |
          black --check src
      - name: Run mypy
        env:
          PYTHONPATH: "src"
        run: |
          mypy src
      - name: Run pylint
        env:
          PYTHONPATH: "src"
        run: |
          pylint src
